[package]
name = "task"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.37", features = ["derive"] }
fs_extra = "1.3.0"
zip = "2.6.1"
zip-extensions = "0.8.3"
