name: Cleanup Artifacts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-24.04
    steps:
      - name: Delete artifacts older than 7 days via API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CUTOFF=$(date -u --date='7 days ago' +"%Y-%m-%dT%H:%M:%SZ")
          PAGE=1
          while :
          do
            RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?page=$PAGE&per_page=100")
            ARTIFACT_IDS=$(echo "$RESPONSE" | jq --arg cutoff "$CUTOFF" -r '.artifacts[] | select(.created_at < $cutoff) | .id')
            if [ -z "$ARTIFACT_IDS" ]; then
              break
            fi
            echo "$ARTIFACT_IDS" | while read ID; do
              curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ID"
              echo "Deleted Artifact ID: $ID"
            done
            ((PAGE++))
          done
          echo "Cleanup completed."